### ISSUE TITLE
config

### ISSUE THREAD

**Issue by SuperJunier666** [qizhaoaoe/transunet#1]
你好，你的config 没有hidden_ch这个参数导致网络跑不通，怎么解决呢

**Comment by qizhaoaoe** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yjsb** [comment]
您好，现在您解决了吗？

**Comment by qizhaoaoe** [comment]
已修改代码。
